spring:
    config:
        import: security-variable.yml
    application:
        name: MarondalGram
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jdbc:mysql://localhost:3306/MarondalGram
        username: root
        password: ${mysql.password}